version: '3.8'

services:
  journal-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: journal-api
    restart: unless-stopped
    
    # Environment variables
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_EnableDiagnostics=0
      # Supabase configuration (override with Coolify environment variables)
      - SUPABASE_URL=${SUPABASE_URL:-http://localhost:54321}
      - SUPABASE_KEY=${SUPABASE_KEY:-your-service-role-key}
      
    # Coolify handles port mapping automatically
    expose:
      - "8080"
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Temporarily disable read-only for debugging
    # read_only: true
    # tmpfs:
    #   - /tmp
    #   - /var/tmp
    
