version: '3.8'

services:
  journal-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: journal-api
    restart: unless-stopped
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_EnableDiagnostics=0
      - SUPABASE_URL=${SUPABASE_URL:-http://localhost:54321}
      - SUPABASE_KEY=${SUPABASE_KEY:-your-service-role-key}
      
    labels:
      - traefik.enable=true
      - "traefik.http.routers.journal-api.rule=Host(`${SERVICE_FQDN_JOURNAL_API}`)"
      - "traefik.http.routers.journal-api.entrypoints=web"
      - "traefik.http.routers.journal-api-secure.rule=Host(`${SERVICE_FQDN_JOURNAL_API}`)"
      - "traefik.http.routers.journal-api-secure.entrypoints=websecure"
      - "traefik.http.routers.journal-api-secure.tls=true"
      - "traefik.http.services.journal-api.loadbalancer.server.port=8080"
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    security_opt:
      - no-new-privileges:true
    
    networks:
      - coolify

networks:
  coolify:
    external: true